# Sample config.toml file to show the most frequently used configuration parameters.

ZOTERO_LIBRARY_ID = "0000000"  # Set this to your Zotero library ID.
ZOTERO_LIBRARY_TYPE = "group"  # Set to "user" for a personal library.

BABEL_DEFAULT_LOCALE = "en_US"
BABEL_DEFAULT_TIMEZONE = "UTC"

#LOGGING_HANDLER = "syslog"    # For Unix only. Recommended when running in production.
#LOGGING_ADDRESS = "/dev/log"  # For Unix only. Recommended when running in production.

#EXPLAIN_TEMPLATE_LOADING = true  # Can be useful for debugging purposes. Do not use in production.

# Most parameters have a default value. Deleting such parameter from this file
# will not disable it but merely reset it to its default value.

[kerko.features]

download_attachment_new_window = false
download_results_link = true
download_results_max_count = 0
open_in_zotero_app = false
open_in_zotero_web = false
print_item_link = false
print_results_link = false
print_results_max_count = 0
relations_links = false
relations_initial_limit = 5
relations_sort = "author_asc"
results_abstracts = false
results_abstracts_max_length = 0
results_abstracts_max_length_leeway = 0
results_abstracts_toggler = true
results_attachment_links = true
results_url_links = true

[kerko.feeds]

formats = ["atom"]
fields = ["id", "data"]
max_days = 0

[kerko.meta]

title = "KerkoApp"
highwirepress_tags = true
google_analytics_id = ""

[kerko.pagination]

page_len = 20
pager_links = 4

[kerko.zotero]

# Changing any of the following will require sync cache --full && sync index.

csl_style = "apa"
locale = "en-US"
item_include_re = ''
item_exclude_re = ''
child_include_re = ''
child_exclude_re = '^_'
attachment_mime_types = ["application/pdf"]
tag_include_re = ''
tag_exclude_re = '^_'

[kerko.search]

fulltext = true         # Changing this will require sync cache --full && sync index.
whoosh_language = "en"  # Changing this will require sync index --full.

[kerko.facets]

    # Changing any facet will require clean index && sync index.

    [kerko.facets.tag]
    enabled = true
    weight = 100
    initial_limit = 10
    initial_limit_leeway = 2
    sort_by = ["label"]

    [kerko.facets.item_type]
    enabled = true
    weight = 200
    initial_limit = 0
    initial_limit_leeway = 2
    sort_by = ["label"]

    [kerko.facets.year]
    enabled = true
    weight = 300
    initial_limit = 0
    initial_limit_leeway = 2
    sort_by = ["label"]

    [kerko.facets.link]
    enabled = false
    weight = 400
    sort_by = ["label"]

    # This shows how a collection-based facet might be configured.
    [kerko.facets.my_custom_facet]
    enabled = false  # No effect unless this is set to true.
    type = "collection"
    collection_key = "AAAAAAAA"
    filter_key = "my_custom_facet"
    title = "My custom facet"
    weight = 50
    initial_limit = 10
    initial_limit_leeway = 2
    sort_by = ["count", "label"]
    sort_reverse = false
    item_view = true

[kerkoapp.proxy_fix]

enabled = false
x_for = 1
x_proto = 1
x_host = 0
x_port = 0
x_prefix = 0
